apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-deployment
  labels:
    app: greeter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greeter
  strategy:
    type: RollingUpdate
    rollingupdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: greeter
    spec:
      containers:
      - name: greeter
        image: greeter:latest
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: HELLO_TAG
          value: "Production-Ready"
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10



